fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

portfolio:
    resource: "@EncryptBundle/Controller/"
    type:     annotation
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: encrypted_files
        permanent: true

